#!/usr/bin/env bash
# =============================================================================
# Auto-generated by rushbuild — acceptance tests for /e/Projects/github/runplus-community/rushbuild/dist-demo-app/demo-app.run.sh
# Run:  bash /e/Projects/github/runplus-community/rushbuild/dist-demo-app/demo-app.run.sh.test.sh
# =============================================================================
set -euo pipefail

RUNNER="/e/Projects/github/runplus-community/rushbuild/dist-demo-app/demo-app.run.sh"
MODULE_NAME="demo-app"
MODULE_SAFE="demo-app"

PASS=0; FAIL=0
_pass() { echo "  ✓ $*"; (( PASS++ )) || true; }
_fail() { echo "  ✗ $*" >&2; (( FAIL++ )) || true; }

assert_exit() {
    local desc="$1" want="$2"; shift 2
    local got=0
    "$@" >/dev/null 2>&1 || got=$?
    [[ "${got}" -eq "${want}" ]] && _pass "${desc} (exit ${got})" \
                                 || _fail "${desc}: expected exit ${want}, got ${got}"
}

assert_file_exists() {
    local desc="$1" path="$2"
    [[ -e "${path}" ]] && _pass "${desc}" || _fail "${desc}: '${path}' not found"
}

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " rushbuild acceptance tests"
echo " module : ${MODULE_NAME}"
echo " runner : ${RUNNER}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# T-01  Runner file exists and is executable
echo ""; echo "[T-01] Runner file"
assert_file_exists "runner .sh exists" "${RUNNER}"
[[ -x "${RUNNER}" ]] && _pass "runner is executable" || _fail "runner is not executable"

# T-02  Rust toolchain available
echo ""; echo "[T-02] Rust toolchain"
assert_exit "cargo is on PATH" 0 cargo --version
assert_exit "rustc is on PATH" 0 rustc --version

# T-03  First run → cache miss + build
echo ""; echo "[T-03] First run — cache miss & build"
TEST_HOME="$(mktemp -d)"
trap 'rm -rf "${TEST_HOME}"' EXIT

FIRST_OUT="$(MMM_HOME="${TEST_HOME}" "${RUNNER}" 2>&1 || true)"
echo "${FIRST_OUT}" | grep -q "Cache miss" \
    && _pass "first run reported cache miss" \
    || _fail "expected 'Cache miss'; got: ${FIRST_OUT}"
echo "${FIRST_OUT}" | grep -q "Build complete" \
    && _pass "first run reported build complete" \
    || _fail "expected 'Build complete'; got: ${FIRST_OUT}"

# T-04  Second run same MMM_HOME → cache hit, no rebuild
echo ""; echo "[T-04] Second run — cache hit"
SECOND_OUT="$(MMM_HOME="${TEST_HOME}" "${RUNNER}" 2>&1 || true)"
echo "${SECOND_OUT}" | grep -q "Cache hit" \
    && _pass "second run reported cache hit" \
    || _fail "expected 'Cache hit'; got: ${SECOND_OUT}"
echo "${SECOND_OUT}" | grep -qv "Build complete" \
    && _pass "second run did not rebuild" \
    || _fail "unexpected 'Build complete' on second run"

# T-05  Fresh MMM_HOME → cache miss again
echo ""; echo "[T-05] Fresh MMM_HOME → cache miss"
TEST_HOME2="$(mktemp -d)"
FRESH_OUT="$(MMM_HOME="${TEST_HOME2}" "${RUNNER}" 2>&1 || true)"
echo "${FRESH_OUT}" | grep -q "Cache miss" \
    && _pass "fresh home caused cache miss" \
    || _fail "expected cache miss with fresh home; got: ${FRESH_OUT}"
rm -rf "${TEST_HOME2}"

# T-06  Payload checksum verified on first build
echo ""; echo "[T-06] Payload checksum verification"
echo "${FIRST_OUT}" | grep -q "Payload checksum verified" \
    && _pass "checksum verified message present" \
    || _fail "expected checksum verification in output; got: ${FIRST_OUT}"

# T-07  Arg forwarding
echo ""; echo "[T-07] Arg forwarding"
SENTINEL="rushbuild_arg_test_$$"
ARG_OUT="$(MMM_HOME="${TEST_HOME}" "${RUNNER}" --rushbuild-test "${SENTINEL}" 2>&1 || true)"
if echo "${ARG_OUT}" | grep -q "${SENTINEL}"; then
    _pass "sentinel arg echoed back by binary"
elif echo "${ARG_OUT}" | grep -qiE "unknown|flag|unrecognized|invalid"; then
    _pass "binary received and rejected unknown flag (forwarding confirmed)"
else
    _fail "could not confirm arg forwarding; output: ${ARG_OUT}"
fi

# T-08  Exit-code forwarding
echo ""; echo "[T-08] Exit-code forwarding"
BINARY_PATH="$(find "${TEST_HOME}/rushbuild/${MODULE_SAFE}/bin" -name 'app*' 2>/dev/null | head -n 1)"
if [[ -z "${BINARY_PATH}" ]]; then
    _fail "could not locate compiled binary under MMM_HOME for exit-code comparison"
else
    RUNNER_EXIT=0
    BINARY_EXIT=0
    MMM_HOME="${TEST_HOME}" "${RUNNER}" --rushbuild-test "${SENTINEL}" >/dev/null 2>&1 || RUNNER_EXIT=$?
    "${BINARY_PATH}" --rushbuild-test "${SENTINEL}" >/dev/null 2>&1 || BINARY_EXIT=$?
    [[ "${RUNNER_EXIT}" -eq "${BINARY_EXIT}" ]] \
        && _pass "runner exit code matches built binary (exit ${RUNNER_EXIT})" \
        || _fail "runner exit ${RUNNER_EXIT} did not match built binary exit ${BINARY_EXIT}"
fi

# T-09  Cache dir layout
echo ""; echo "[T-09] Cache directory layout"
BIN_COUNT="$(find "${TEST_HOME}/rushbuild/${MODULE_SAFE}/bin" -name 'app*' 2>/dev/null | wc -l | tr -d ' ')"
[[ "${BIN_COUNT}" -ge 1 ]] \
    && _pass "compiled binary found under MMM_HOME/rushbuild/${MODULE_SAFE}/bin/" \
    || _fail "no compiled binary found under expected path"

# T-10  Payload marker present
echo ""; echo "[T-10] Payload integrity"
grep -q '^__PAYLOAD_B64__$' "${RUNNER}" \
    && _pass "__PAYLOAD_B64__ marker present in runner" \
    || _fail "__PAYLOAD_B64__ marker missing — runner is malformed"

# T-11  Runner bash syntax check
echo ""; echo "[T-11] Runner syntax"
bash -n "${RUNNER}" \
    && _pass "runner passes bash -n syntax check" \
    || _fail "runner failed bash -n syntax check"

# T-12  Corruption detection — tamper with payload, expect checksum error
echo ""; echo "[T-12] Corruption detection"
CORRUPT_RUNNER="$(mktemp)"
cp "${RUNNER}" "${CORRUPT_RUNNER}"
chmod +x "${CORRUPT_RUNNER}"
MARKER_LINE="$(grep -n '^__PAYLOAD_B64__$' "${CORRUPT_RUNNER}" | cut -d: -f1)"
# IMPORTANT: base64 output may not contain a predictable character on any
# particular line (wrapping at ~76 chars). So we corrupt the *first non-empty*
# payload line by flipping its first character deterministically.
TMP_CORRUPT="$(mktemp)"
awk -v m="${MARKER_LINE}" '
  NR<=m { print; next }
  (!mod && length($0)>0) {
    c=substr($0,1,1);
    r=(c=="A"?"B":"A");
    $0=r substr($0,2);
    mod=1;
  }
  { print }
  END { if(!mod) exit 2 }
' "${CORRUPT_RUNNER}" > "${TMP_CORRUPT}" \
  && mv "${TMP_CORRUPT}" "${CORRUPT_RUNNER}" \
  || { rm -f "${TMP_CORRUPT}"; true; }
chmod +x "${CORRUPT_RUNNER}" 2>/dev/null || true
CORRUPT_HOME="$(mktemp -d)"
CORRUPT_OUT="$(MMM_HOME="${CORRUPT_HOME}" "${CORRUPT_RUNNER}" 2>&1 || true)"
echo "${CORRUPT_OUT}" | grep -qiE "checksum mismatch|corrupted" \
    && _pass "corrupted runner detected and rejected" \
    || _fail "expected checksum mismatch error; got: ${CORRUPT_OUT}"
rm -rf "${CORRUPT_HOME}" "${CORRUPT_RUNNER}"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
TOTAL=$(( PASS + FAIL ))
echo " Results: ${PASS}/${TOTAL} passed, ${FAIL} failed"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
[[ "${FAIL}" -eq 0 ]] && exit 0 || exit 1
