#!/usr/bin/env bash
# ----------------------------------------------------------------------------
# Auto-generated by rushbuild — DO NOT EDIT
# Self-contained Rust crate runner — works on Linux (GH Actions) and macOS
# ----------------------------------------------------------------------------
set -euo pipefail

# ── Portability helpers ───────────────────────────────────────────────────

# sha256 of a file — supports GNU (sha256sum) and BSD/macOS (shasum)
_sha256_file() {
    if command -v sha256sum &>/dev/null; then
        sha256sum "$1" | awk '{print $1}'
    elif command -v shasum &>/dev/null; then
        shasum -a 256 "$1" | awk '{print $1}'
    else
        echo "🔴 [rushbuild] ERROR: no sha256 tool found (sha256sum or shasum required)" >&2; exit 1
    fi
}

# sha256 of a string
_sha256_str() {
    if command -v sha256sum &>/dev/null; then
        printf '%s' "$1" | sha256sum | awk '{print $1}'
    elif command -v shasum &>/dev/null; then
        printf '%s' "$1" | shasum -a 256 | awk '{print $1}'
    else
        echo "🔴 [rushbuild] ERROR: no sha256 tool found" >&2; exit 1
    fi
}

# base64 decode from stdin — GNU uses --decode, BSD/macOS uses -D
_b64_decode() {
    if base64 --decode /dev/null &>/dev/null 2>&1; then
        base64 --decode
    else
        base64 -D
    fi
}

_is_truthy() {
    case "${1:-}" in
        1|true|TRUE|yes|YES|on|ON)
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

_enable_verbose_logging() {
    local log_file="$1"

    mkdir -p "$(dirname "${log_file}")"
    : > "${log_file}"

    if command -v tee >/dev/null 2>&1; then
        exec > >(tee -a "${log_file}") 2>&1
    else
        exec >> "${log_file}" 2>&1
    fi

    echo "📜 [rushbuild] Transcript → ${log_file}"

    if _is_truthy "${RUSHBUILD_TRACE:-0}"; then
        set -x
    fi
}

_rust_host() {
    rustc -vV 2>/dev/null | awk -F': ' '/^host:/ {print $2; found=1} END {if(!found) exit 1}' \
        || printf '%s-%s\n' "$(uname -m)" "$(uname -s | tr '[:upper:]' '[:lower:]')"
}

# Clear a directory's contents before re-extracting sources.
# This avoids stale files surviving across payload changes.
_clear_dir_contents() {
    local dir="$1"
    local entries=()

    mkdir -p "${dir}"
    shopt -s dotglob nullglob
    entries=( "${dir}"/* )
    shopt -u dotglob nullglob

    if (( ${#entries[@]} > 0 )); then
        rm -rf "${entries[@]}"
    fi
}

# ── 1. Identity & home ────────────────────────────────────────────────────
MODULE_SAFE="demo-app"
BINARY_NAME="demo-app"
PAYLOAD_SHA256="3338d1bfe925632efdd4a9f068d7876d5627227d09bf74f99b1c85602766929e"   # sha256 of the embedded tar.gz;
                                       # any source change → new hash → rebuild

# MMM_HOME lets CI pin the cache to a persistent volume between runs.
BASE_HOME="${MMM_HOME:-${TMPDIR:-/tmp}}"
APP_HOME="${BASE_HOME}/rushbuild/${MODULE_SAFE}"
CARGO_HOME="${APP_HOME}/cargo-home"
CARGO_TARGET_DIR="${APP_HOME}/cargo-target"

SRC_DIR="${APP_HOME}/src"
BIN_DIR="${APP_HOME}/bin"
OUT_DIR="${APP_HOME}/out"
DECODE_TMP="${APP_HOME}/payload_verify.tar.gz"  # temp file used for checksum check

mkdir -p "${SRC_DIR}" "${BIN_DIR}" "${OUT_DIR}" "${CARGO_HOME}" "${CARGO_TARGET_DIR}"
export CARGO_HOME CARGO_TARGET_DIR

# ── 2. Cache key ──────────────────────────────────────────────────────────
# Four-part key — all must match or binary is rebuilt:
#   module_safe → isolates projects sharing the same MMM_HOME
#   rust host   → arch/OS mismatch → rebuild
#   rustc       → toolchain upgrade → rebuild
#   payload sha → source change → rebuild
RUST_HOST="$(_rust_host)"
RUSTC_VERSION="$(rustc --version 2>/dev/null | awk '{print $2}' || echo 'unknown')"

CACHE_KEY="${MODULE_SAFE}__${RUST_HOST}__rustc-${RUSTC_VERSION}__${PAYLOAD_SHA256}"
CACHE_KEY_HASH="$(_sha256_str "${CACHE_KEY}")"

EXE_SUFFIX=""
case "$(uname -s 2>/dev/null || printf unknown)" in
    MINGW*|MSYS*|CYGWIN*) EXE_SUFFIX=".exe" ;;
esac

BINARY="${BIN_DIR}/${CACHE_KEY_HASH}/app${EXE_SUFFIX}"

if _is_truthy "${RUSHBUILD_VERBOSE:-0}"; then
    RUNNER_LOG_DIR="${RUSHBUILD_LOG_DIR:-${APP_HOME}/logs}"
    _enable_verbose_logging "${RUNNER_LOG_DIR}/runner-${CACHE_KEY_HASH}-$$.log"
fi

# ── 3. Build (cache miss path) ────────────────────────────────────────────
if [[ ! -x "${BINARY}" ]]; then
    echo "[rushbuild] Cache miss - building ${MODULE_SAFE} (${RUST_HOST}, rustc ${RUSTC_VERSION})" >&2

    # 3a. Find the payload marker line
    PAYLOAD_LINE="$(grep -n '^__PAYLOAD_B64__$' "$0" | cut -d: -f1)"
    if [[ -z "${PAYLOAD_LINE}" ]]; then
        echo "🔴 [rushbuild] ERROR: payload marker not found in runner script" >&2
        exit 1
    fi
    PAYLOAD_START=$(( PAYLOAD_LINE + 1 ))

    # 3b. Decode into a temp file, then verify sha256 BEFORE extracting.
    #     If the runner was truncated or corrupted, we fail fast with a clear message
    #     rather than letting tar produce a confusing partial extraction.
    tail -n "+${PAYLOAD_START}" "$0" | _b64_decode > "${DECODE_TMP}"

    ACTUAL_SHA="$(_sha256_file "${DECODE_TMP}")"
    if [[ "${ACTUAL_SHA}" != "${PAYLOAD_SHA256}" ]]; then
        echo "🔴 [rushbuild] ERROR: payload checksum mismatch — runner may be corrupted!" >&2
        echo "   expected : ${PAYLOAD_SHA256}" >&2
        echo "   actual   : ${ACTUAL_SHA}" >&2
        rm -f "${DECODE_TMP}"
        exit 1
    fi
    echo "✅ [rushbuild] Payload checksum verified (${ACTUAL_SHA:0:12}…)" >&2

    # 3c. Clear any previously extracted tree so deleted files do not linger.
    _clear_dir_contents "${SRC_DIR}"

    # 3d. Unpack verified tarball
    tar -xz -C "${SRC_DIR}" --strip-components=1 < "${DECODE_TMP}"
    rm -f "${DECODE_TMP}"

    # 3e. Compile
    mkdir -p "$(dirname "${BINARY}")"
    echo "[rushbuild] cargo build --release -> ${BINARY}" >&2
    (cd "${SRC_DIR}" && cargo build --release --locked) \
        || { echo "ERROR: cargo build failed" >&2; exit 1; }

    BUILT_BINARY="${CARGO_TARGET_DIR}/release/${BINARY_NAME}${EXE_SUFFIX}"
    if [[ ! -x "${BUILT_BINARY}" ]]; then
        echo "ERROR: built binary not found: ${BUILT_BINARY}" >&2
        exit 1
    fi
    cp "${BUILT_BINARY}" "${BINARY}"
    chmod +x "${BINARY}"

    echo "[rushbuild] Build complete -> ${BINARY}" >&2
else
    echo "[rushbuild] Cache hit -> ${BINARY}" >&2
fi

# ── 4. Exec — forward ALL CLI args seamlessly ─────────────────────────────
# exec replaces this shell process with the Rust binary — no PID wrapper,
# signals propagate directly, exit codes are exact.
# "$@" preserves every argument exactly as the caller passed them.
exec "${BINARY}" "$@"

# (Never reached — exec replaced this process)
__PAYLOAD_B64__
H4sIAAAAAAAAA+2XS2+bQBDHfeZTTMkFpEJ5Gsl5qFJOPfWQqhfLqjAMzjawIHaJEiX+7h3A76R5
SLajqvu7APuanf3v7A51I6SVYlF+GRwMh4jCcOAMHTca9k/HcbvyBQM3dKModIPIo3LXDwN/AOHh
prSG/I9rgMFlmeLdVczTaXn3PctyxvEY5j+aeqW/ncT17CDb4P36B5EbKP2PwRP9k5JnbGbLssj3
ZaMVeBgE79A/cqg5OPuawEso/Rf6X7by23mZ3Ozbxmv6e/5C/8CjGp/0p+M/UvofgxP4cc0EZCxH
oGfcUODHkiVxnt/D1xlyrGOJKUzvod8g2gl8k21TXtKDS+QpVWdlDUXMmzgHTJlkfGZrt1gLVnI4
h0DTxuMqTm7iGU4mGo8LpFK93XZWXFX6RlPdsV3b0bWPXpf/hd343+e5v+S1+He9VfyHQeB08T/0
Vfwfg1VYvikqu9juSzzHc3WK6xSr9gjgCUMx0VTc/mOs41/UyYH+Ad+c/3fx3+X/vu+p/P8YbOtf
xIzbtdizjVfOf5eyvh39w6Gnzv+j0AgEIdPRCPntqbb6quoyQSFONS3j0O4Kw4QHDYgcJVCmIEbw
E5OzK1lTrndBFwL1H43aCsO0xQ2rDNe0kzLPMZGGSeO0fVnWdbWZ+IVFJe9p0MfHrmjsTOCcbhXL
usa80neL+8J+Ai0VWZU5/2Ssbyuy8bS2EXS1jZ6vA1j2hbFlURxcTxuWp5ZEIeFMIKcsFvOLCYzx
jsnAo5du8rY92RywRtnUvP+eb7m59ml78E1HqGm7oFdlgcbSpEmr2VmaoaRV3Gi97cDDssN8cz67
c+rntXzDdfeCCUHawXKU7VXq5KddQa4bnvmSe/3qPK/Oou6vIwc7Q284N9c/96vwu6Tdp4NuUtO5
yi8UCoVCoVAoFAqFQqFQKBSKd/AHGX0AQAAoAAA=
